version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: charles30
      POSTGRES_DB: library_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network

  api:
    build: .
    container_name: library_api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://library_user:charles30@postgres:5432/library_db
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - library_network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run db:seed &&
        npm start
      "

  adminer:
    image: adminer
    container_name: library_adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - library_network

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge
